version: "3"
services:
  jupyter:
    image: alpeza/mllab:1.0.0
    deploy:
      replicas: 1
    environment:
      - CONNECT_COLAB=0
    ports:
      - "8881:8888"
    volumes:
      - ./notebooks/notebook_1:/opt/notebooks
